spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1  #根据profiles指定主机名
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/  #将自己注册到peer2
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2  #根据profiles指定主机名
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/  #将自己注册到peer2